<?php
namespace app\index\controller;

class Tecsun extends Base
{
	/*研习会*/
	public function yanxihui()
	{
		$yanxihui = db( 'wenjuan' )->where( 'type', 1 )->paginate( 5 );
		$this->assign( 'list', $yanxihui );
		return $this->fetch();		
	}

	// 研习会详细信息
	public function yanxihuiDetail()
	{
		$id       = input( 'id' ); 
        $yanxihui = db( 'wenjuan' )->where( 'id',input( 'id' ) )->find();
        $this->assign( 'type', '研习会调查问卷' );
        $this->assign( 'list', $yanxihui );
        return $this->fetch( 'detail' );
	}

	// 删除问卷记录 包含了研习会、售前、售后 单个和批量选定的删除方法
	public function wenjuanDel()
	{
		// 这里缺少对传递的数据进行验证
        // 批量删除记录是不需要跳转页面，也就不需要区分是那种类型，单个删除是需要跳转到对应的页面
        $id[] = input( 'post.id/a' );
        // 批量删除时，把所有的id存放在$id[0]当中，通过判断$id[0]是否为空区分是否是批量删除的方式
        if( $id[0] ){
            // 暂时没有找到批量删除的方法，所以只能通过for方法循环删除
            for( $i=0 ; $i<count($id[0]) ; $i++ )
            {
                $data   = ["id" => $id[0][$i]];
                $dels[] = db( 'wenjuan' )->delete( $data );
            }
            // 这里缺少返回json标识数据
            print_r($dels);
        } else {
            // 判定为单独删除数据
            // 获取要删除的id
            $id      = input('id');
            // 通过id查找要输出的数据
            $wenjuan = db( 'wenjuan' )->where( 'id', $id )->find();
            // print_r($wenjuan);exit;
            // 通过id删除指定数据
            $dels = db( 'wenjuan' )->delete( $id );
            // 通过上面查找出的数据，判定是那种类型的数据，然后跳转到对应的页面
            if( $wenjuan['type'] == 1 )
            {
                // 删除的数据类型为研习会
                return $this->redirect( 'yanxihui' );
            } else if( $wenjuan['type'] == 2 ) {
                // 删除的数据类型为售前
                return $this->redirect( 'shouqian' );                
            } else if( $wenjuan['type'] == 3 ) {
                // 删除的数据类型为售后
                return $this->redirect( 'shouhou' );
            } else {

            }
            // return $this->;
        }
        // print_r($id);exit; 
	}

	/*清空所有研习会问卷记录*/
	public function yanxihuiDelAll()
	{
        // 限制id要大于1
		$map['id']   = ['>' , 1];
        // 限定数据类型为1，即使研习会
        $map['type'] = 1;
        // 获取所有的研习会的id
        $delid = db( 'wenjuan' )->where( $map )->column( 'id' );
        // 批量删除所有的研习会问卷数据
        $dels  = db( 'wenjuan' )->delete( $delid );
        print_r( $dels );
	}

	/*导出选定问卷记录*/
	public function yanxihuiExport()
	{
        // 引入库文件
        \think\Loader::import('Excel.PHPExcel');
        \think\Loader::import('Excel.PHPExcel.IOFactory');
        
        $id[] = input('post.id/a');
        // print_r($id);die;
        for($i=0 ; $i<count($id[0]) ; $i++)
        {
            $epl[] = db('wenjuan')->where('id',$id[0][$i])->find();
        }
        // print_r($epl);die;
        // 拼接文件名
        $fileName = "bufenYanxihui".date("Ymd-His",time()).".xls";


        $objExcel = new \PHPExcel();  // 创建一个处理对象实例
        // 创建文件格式写入对象实例, uncomment
        $objWriter = new \PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式

        //*************************************
        //设置文档基本属性
        $objProps = $objExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        //*************************************
        //设置当前的sheet索引，用于后续的内容操作。
        //一般只有在使用多个sheet的时候才需要显示调用。
        //缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0

        $objExcel->setActiveSheetIndex(0);
        $objActSheet = $objExcel->getActiveSheet();

        //设置当前活动sheet的名称
        $objActSheet->setTitle("问卷记录");

        //设置单元格首格内容
        $objActSheet->setCellValue('A1','问题1');
        $objActSheet->setCellValue('B1','问题2');
        $objActSheet->setCellValue('C1','问题3');
        $objActSheet->setCellValue('D1','问题4');
        $objActSheet->setCellValue('E1','问题5');
        $objActSheet->setCellValue('F1','问题6');
        $objActSheet->setCellValue('G1','问题7');
        $objActSheet->setCellValue('H1','问题8');
        $objActSheet->setCellValue('I1','奖品');
        $objActSheet->setCellValue('J1','研习会期数');
        // $objActSheet->setCellValue('K1','填写时间');

        //  遍历访客信息数组，将数据存入对应的excel文件的每个单元格
        for($i = 0; $i < count($epl); $i++)
        {
            $objExcel->getActiveSheet()->setCellValueExplicit('A'.($i+2),$epl[$i]['q1']);
            $objExcel->getActiveSheet()->setCellValueExplicit('B'.($i+2),$epl[$i]['q2']);
            $objExcel->getActiveSheet()->setCellValueExplicit('C'.($i+2),$epl[$i]['q3']);
            $objExcel->getActiveSheet()->setCellValueExplicit('D'.($i+2),$epl[$i]['q4']);
            $objExcel->getActiveSheet()->setCellValueExplicit('E'.($i+2),$epl[$i]['q5']);
            $objExcel->getActiveSheet()->setCellValueExplicit('F'.($i+2),$epl[$i]['q6']);
            $objExcel->getActiveSheet()->setCellValueExplicit('G'.($i+2),$epl[$i]['q7']);
            $objExcel->getActiveSheet()->setCellValueExplicit('H'.($i+2),$epl[$i]['q8']);
            $objExcel->getActiveSheet()->setCellValueExplicit('I'.($i+2),$epl[$i]['jiang']);
            $objExcel->getActiveSheet()->setCellValueExplicit('J'.($i+2),$epl[$i]['qi']);
        }


        //*************************************
        //设置单元格样式
        //

        //设置宽度
        $objActSheet->getColumnDimension('A')->setWidth(14.5);
        $objActSheet->getColumnDimension('B')->setWidth(14.5);
        $objActSheet->getColumnDimension('C')->setWidth(14.5);
        $objActSheet->getColumnDimension('D')->setWidth(14.5);
        $objActSheet->getColumnDimension('E')->setWidth(14.5);
        $objActSheet->getColumnDimension('F')->setWidth(14.5);
        $objActSheet->getColumnDimension('G')->setWidth(14.5);
        $objActSheet->getColumnDimension('H')->setWidth(14.5);
        $objActSheet->getColumnDimension('I')->setWidth(14.5);
        $objActSheet->getColumnDimension('J')->setWidth(14.5);

        //设置字体
        $objStyleA = $objActSheet->getStyle('A');
        $objStyleA = $objStyleA->getFont();
        $objStyleA->setName('宋体');
        $objStyleA->setSize(10);
        $objStyleA->setBold(true);
        $objStyleA->getColor()->setARGB('FF999999');

        //*************************************
        //输出内容

        $outputFileName = $fileName;
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header('Content-Disposition:attachment;filename="' . $outputFileName . '"');//兼容其他浏览器到文件
        header('Content-Disposition:filename="' . $outputFileName . '"');  //兼容IE浏览器到文件
        header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
        header("Content-Transfer-Encoding: binary");
        header("Expires: 0");
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Pragma: no-cache");
        $objWriter->save('./excel/'.$outputFileName);
        echo $outputFileName;
    }

    /*导出所有问卷记录*/
	public function yanxihuiExportAll()
	{
        // 引入库文件
        \think\Loader::import('Excel.PHPExcel');
        \think\Loader::import('Excel.PHPExcel.IOFactory');
        

        $map['id']   = ['>' , 1];
        $map['type'] = 1;
        $epls[] = db('wenjuan')->where($map)->select();
        $epl    = $epls[0];
 
        // print_r($epl);die;
        // 拼接文件名
        $fileName = "quanbuYanxihui".date("Ymd-His",time()).".xls";


        $objExcel = new \PHPExcel();  // 创建一个处理对象实例
        // 创建文件格式写入对象实例, uncomment
        $objWriter = new \PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式

        //*************************************
        //设置文档基本属性
        $objProps = $objExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        //*************************************
        //设置当前的sheet索引，用于后续的内容操作。
        //一般只有在使用多个sheet的时候才需要显示调用。
        //缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0

        $objExcel->setActiveSheetIndex(0);
        $objActSheet = $objExcel->getActiveSheet();

        //设置当前活动sheet的名称
        $objActSheet->setTitle("问卷记录");

        //设置单元格首格内容
        $objActSheet->setCellValue('A1','问题1');
        $objActSheet->setCellValue('B1','问题2');
        $objActSheet->setCellValue('C1','问题3');
        $objActSheet->setCellValue('D1','问题4');
        $objActSheet->setCellValue('E1','问题5');
        $objActSheet->setCellValue('F1','问题6');
        $objActSheet->setCellValue('G1','问题7');
        $objActSheet->setCellValue('H1','问题8');
        $objActSheet->setCellValue('I1','奖品');
        $objActSheet->setCellValue('J1','研习会期数');
        // $objActSheet->setCellValue('K1','填写时间');

        //  遍历访客信息数组，将数据存入对应的excel文件的每个单元格
        for($i = 0; $i < count($epl); $i++)
        {
            $objExcel->getActiveSheet()->setCellValueExplicit('A'.($i+2),$epl[$i]['q1']);
            $objExcel->getActiveSheet()->setCellValueExplicit('B'.($i+2),$epl[$i]['q2']);
            $objExcel->getActiveSheet()->setCellValueExplicit('C'.($i+2),$epl[$i]['q3']);
            $objExcel->getActiveSheet()->setCellValueExplicit('D'.($i+2),$epl[$i]['q4']);
            $objExcel->getActiveSheet()->setCellValueExplicit('E'.($i+2),$epl[$i]['q5']);
            $objExcel->getActiveSheet()->setCellValueExplicit('F'.($i+2),$epl[$i]['q6']);
            $objExcel->getActiveSheet()->setCellValueExplicit('G'.($i+2),$epl[$i]['q7']);
            $objExcel->getActiveSheet()->setCellValueExplicit('H'.($i+2),$epl[$i]['q8']);
            $objExcel->getActiveSheet()->setCellValueExplicit('I'.($i+2),$epl[$i]['jiang']);
            $objExcel->getActiveSheet()->setCellValueExplicit('J'.($i+2),$epl[$i]['qi']);
            // $objExcel->getActiveSheet()->setCellValueExplicit('J'.($i+2),$epl[$i]['qi']);
        }

        //显式指定内容类型
        /*$objActSheet->setCellValueExplicit('A5', '847475847857487584',
            PHPExcel_Cell_DataType::TYPE_STRING);*/

        //合并单元格
        /*$objActSheet->mergeCells('B1:C22');

        //分离单元格
        $objActSheet->unmergeCells('B1:C22');*/

        //*************************************
        //设置单元格样式
        //

        //设置宽度
        $objActSheet->getColumnDimension('A')->setWidth(14.5);
        $objActSheet->getColumnDimension('B')->setWidth(14.5);
        $objActSheet->getColumnDimension('C')->setWidth(14.5);
        $objActSheet->getColumnDimension('D')->setWidth(14.5);
        $objActSheet->getColumnDimension('E')->setWidth(14.5);
        $objActSheet->getColumnDimension('F')->setWidth(14.5);
        $objActSheet->getColumnDimension('G')->setWidth(14.5);
        $objActSheet->getColumnDimension('H')->setWidth(14.5);
        $objActSheet->getColumnDimension('I')->setWidth(14.5);
        $objActSheet->getColumnDimension('J')->setWidth(14.5);

        //设置单元格内容的数字格式。
        //
        //如果使用了 PHPExcel_Writer_Excel5 来生成内容的话，
        //这里需要注意，在 PHPExcel_Style_NumberFormat 类的 const 变量定义的
        //各种自定义格式化方式中，其它类型都可以正常使用，但当setFormatCode
        //为 FORMAT_NUMBER 的时候，实际出来的效果被没有把格式设置为"0"。需要
        //修改 PHPExcel_Writer_Excel5_Format 类源代码中的 getXf($style) 方法，
        //在 if ($this->_BIFF_version == 0x0500) { （第363行附近）前面增加一
        //行代码:
        //if($ifmt === '0') $ifmt = 1;
        //
        //设置格式为PHPExcel_Style_NumberFormat::FORMAT_NUMBER，避免某些大数字
        //被使用科学记数方式显示，配合下面的 setAutoSize 方法可以让每一行的内容
        //都按原始内容全部显示出来。
                /*$objStyleA5
                    ->getNumberFormat()
                    ->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER);*/

        //设置字体
        $objStyleA = $objActSheet->getStyle('A');
        $objStyleA = $objStyleA->getFont();
        $objStyleA->setName('宋体');
        $objStyleA->setSize(10);
        $objStyleA->setBold(true);
        $objStyleA->getColor()->setARGB('FF999999');

        //设置对齐方式
        /*$objAlignA5 = $objStyleA5->getAlignment();
        $objAlignA5->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);
        $objAlignA5->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);

        //设置边框
        $objBorderA5 = $objStyleA5->getBorders();
        $objBorderA5->getTop()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
        $objBorderA5->getTop()->getColor()->setARGB('FFFF0000'); // color
        $objBorderA5->getBottom()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
        $objBorderA5->getLeft()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
        $objBorderA5->getRight()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);

        //设置填充颜色
        $objFillA5 = $objStyleA5->getFill();
        $objFillA5->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
        $objFillA5->getStartColor()->setARGB('FFEEEEEE');

        //从指定的单元格复制样式信息.
        $objActSheet->duplicateStyle($objStyleA5, 'B1:C22');*/


        //*************************************
        //添加图片
        /*$objDrawing = new PHPExcel_Worksheet_Drawing();
        $objDrawing->setName('ZealImg');
        $objDrawing->setDescription('Image inserted by Zeal');
        $objDrawing->setPath('./zeali.net.logo.gif');
        $objDrawing->setHeight(36);
        $objDrawing->setCoordinates('C23');
        $objDrawing->setOffsetX(10);
        $objDrawing->setRotation(15);
        $objDrawing->getShadow()->setVisible(true);
        $objDrawing->getShadow()->setDirection(36);
        $objDrawing->setWorksheet($objActSheet);*/


        //添加一个新的worksheet
        /*$objExcel->createSheet();
        $objExcel->getSheet(1)->setTitle('测试2');

        //保护单元格
        $objExcel->getSheet(1)->getProtection()->setSheet(true);
        $objExcel->getSheet(1)->protectCells('A1:C22', 'PHPExcel');*/


        //*************************************
        //输出内容
        //

        $outputFileName = $fileName;
        // $time = date("Ymd H-i-s",time());
        // $outputFileName = $time.".xls";
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header('Content-Disposition:attachment;filename="' . $outputFileName . '"');//兼容其他浏览器到文件
        header('Content-Disposition:filename="' . $outputFileName . '"');  //兼容IE浏览器到文件
        header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
        header("Content-Transfer-Encoding: binary");
        header("Expires: 0");
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Pragma: no-cache");
        $objWriter->save('./excel/'.$outputFileName);
        echo $outputFileName;
    }

    /*研习会问卷调查设置*/
    public function yanxihuiSettings()
    {
        // 判断时候是POST方式提交数据
        if( Request()->isPost())
        {
            // 获取表单数据
            $data = [
                'qi'          => input( 'post.qi' ),
                'start_time'  => input( 'post.start_time' ),
                'end_time'    => input( 'post.end_time' ),
                'jiang_1_name'=> input( 'post.jiang_1_name' ),
                'jiang_1_num' => input( 'post.jiang_1_num' ),                
                'jiang_2_name'=> input( 'post.jiang_2_name' ),
                'jiang_2_num' => input( 'post.jiang_2_num' ),
                'type'        => 1,
                'status'      => 1,
                'jiang_1_rest'=>input( 'post.jiang_1_num' ),
                'jiang_2_rest'=>input( 'post.jiang_2_num' ),
                'jiang_1_winning' => input( 'post.jiang_1_winning' ),
                'jiang_2_winning' => input( 'post.jiang_2_winning' ),

                // 'create_time' => time(),
            ];
            // print_r($data);die;

            // 转换问卷开始时间和问卷结束时间
            $data['start_time'] = strtotime( $data['start_time'] );
            $data['end_time']   = strtotime( input( 'post.end_time' ) );

            // 判断这条设置是否已经存在
            $yanxihui = db( 'wenjuansettings' )->where( $data )->find();
            if( $yanxihui )
            {   
                // 这条设置已经存在，提示错误信息，返回前端页面
                return $this->error( '您并没有修改问卷设置，请检查设置之后再提交' );
            }
            // 判断当前期数是否存在
            $yanxihui = db( 'wenjuansettings' )->where( [ 'qi' => $data['qi'] ] )->find();
            if( $yanxihui )
            {
                // 当期期数存在，更新当前期数设置
                $data['id'] = $yanxihui['id'];
                $res = db( 'wenjuansettings' )->update( $data );
            } else {
                // 当前期数不存在，新增当前设置
                $data['create_time'] = time();
                $res = db( 'wenjuansettings' )->insert( $data );
            }
            if( $res )
            {
                // 数据操作成功
                return $this->success( '设置成功' );
            } else {
                // 数据操作失败
                return $this->error( '设置失败，请稍后再试' );
            }

        } else {
            // 不是POST方式提交数据
            // 获取当前设置
            $list = db( 'wenjuansettings' )->where( 'type', 1 )->order( 'id desc' )->limit( 1 )->find();
            $this->assign( 'list', $list );
            return $this->fetch();
        }
    }

    /*售前问卷调查设置*/
    public function shouqianSettings()
    {
        // 判断时候是POST方式提交数据
        if( Request()->isPost())
        {
            // 获取表单数据
            $data = [
                'jiang_1_name'=> input( 'post.jiang_1_name' ),
                'jiang_1_num' => input( 'post.jiang_1_num' ),                
                'jiang_2_name'=> input( 'post.jiang_2_name' ),
                'jiang_2_num' => input( 'post.jiang_2_num' ),
                'type'        => 2,
                'status'      => 1,
                'jiang_1_rest'=>input( 'post.jiang_1_num' ),
                'jiang_2_rest'=>input( 'post.jiang_2_num' ),
                'jiang_1_winning' => input( 'post.jiang_1_winning' ),
                'jiang_2_winning' => input( 'post.jiang_2_winning' ),

            ];
            // print_r($data);die;

            // 判断这条设置是否已经存在
            $shouqian = db( 'wenjuansettings' )->where( $data )->find();
            if( $shouqian )
            {   
                // 这条设置已经存在，提示错误信息，返回前端页面
                return $this->error( '您并没有修改问卷设置，请检查设置之后再提交' );
            }
            // 当前期数不存在，新增当前设置
            $data['create_time'] = time();
            $res = db( 'wenjuansettings' )->insert( $data );
            if( $res )
            {
                // 数据操作成功
                return $this->success( '设置成功' );
            } else {
                // 数据操作失败
                return $this->error( '设置失败，请稍后再试' );
            }

        } else {
            // 不是POST方式提交数据
            // 获取当前设置
            $list = db( 'wenjuansettings' )->where( 'type', 2 )->order( 'id desc' )->limit( 1 )->find();
            $this->assign( 'list', $list );
            return $this->fetch();
        }
    }

	/*售前*/
	public function shouqian()
	{
        $shouqian = db( 'wenjuan' )->where( 'type', 2 )->order( 'id desc' )->paginate( 5 );
        $this->assign( 'list', $shouqian );
		return $this->fetch();		
	}

    // 售前详细信息
    public function shouqianDetail()
    {
        $id       = input( 'id' ); 
        $shouqian = db( 'wenjuan' )->where( 'id',input( 'id' ) )->find();
        $this->assign( 'type', '售前调查问卷' );
        $this->assign( 'list', $shouqian );
        return $this->fetch( 'shouqiandetail' );
    }

    /*新增问卷对象*/
    public function shouqianAdd()
    {
        if( Request()->isPost() )
        {
            $data = [
                'name' => input( 'post.name' ),
                'phone'=> input( 'post.phone' ),
                'type' => 2,
            ];
            // 查看是否有没有填写的用户信息
            $wenjuan = db( 'wenjuan' )->where( [ 'phone'=>$data['phone'], 'flag'=>0, 'type' =>2 ] )->find();
            // print_r( $wenjuan );die;
            if( $wenjuan )
            {
                // 存在未处理记录，没有必要添加
                $this->error( '用户还没有填写问卷，请不用着急再次添加' );
            } else {
                // 没有存在未处理记录，添加记录
                $res = db( 'wenjuan' )->insert( $data );
                // 判断插入数据是否成功
                if( $res )
                {
                    // 插入数据成功
                    $this->success( '添加成功' , 'shouqian' );
                } else {
                    // 插入数据失败
                    $this->error( '添加失败' );
                }
            }
            // print_r( $data );
        } else {
            return $this->fetch();
        }
    }

    /*导出选定售前问卷记录*/
    public function shouqianExport()
    {
        // 引入库文件
        \think\Loader::import('Excel.PHPExcel');
        \think\Loader::import('Excel.PHPExcel.IOFactory');
        
        $id[] = input('post.id/a');
        // print_r($id);die;
        for($i=0 ; $i<count($id[0]) ; $i++)
        {
            $epl[] = db('wenjuan')->where('id',$id[0][$i])->find();
        }
        // print_r($epl);die;
        // 拼接文件名
        $fileName = "bufenShouqian".date("Ymd-His",time()).".xls";


        $objExcel = new \PHPExcel();  // 创建一个处理对象实例
        // 创建文件格式写入对象实例, uncomment
        $objWriter = new \PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式

        //*************************************
        //设置文档基本属性
        $objProps = $objExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        //*************************************
        //设置当前的sheet索引，用于后续的内容操作。
        //一般只有在使用多个sheet的时候才需要显示调用。
        //缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0

        $objExcel->setActiveSheetIndex(0);
        $objActSheet = $objExcel->getActiveSheet();

        //设置当前活动sheet的名称
        $objActSheet->setTitle("问卷记录");

        //设置单元格首格内容
        $objActSheet->setCellValue('A1','能否达到预期效果');
        $objActSheet->setCellValue('B1','是否在约定时间内到达');
        $objActSheet->setCellValue('C1','服务态度如何');
        $objActSheet->setCellValue('D1','功能讲解如何');
        $objActSheet->setCellValue('E1','需要提升的地方');
        $objActSheet->setCellValue('F1','客户公司名称');
        $objActSheet->setCellValue('G1','客户姓名');
        $objActSheet->setCellValue('H1','客户手机号码');
        $objActSheet->setCellValue('I1','获得奖品');

        //  遍历访客信息数组，将数据存入对应的excel文件的每个单元格
        for($i = 0; $i < count($epl); $i++)
        {
            $objExcel->getActiveSheet()->setCellValueExplicit('A'.($i+2),$epl[$i]['q1']);
            $objExcel->getActiveSheet()->setCellValueExplicit('B'.($i+2),$epl[$i]['q2']);
            $objExcel->getActiveSheet()->setCellValueExplicit('C'.($i+2),$epl[$i]['q3']);
            $objExcel->getActiveSheet()->setCellValueExplicit('D'.($i+2),$epl[$i]['q4']);
            $objExcel->getActiveSheet()->setCellValueExplicit('E'.($i+2),$epl[$i]['q5']);
            $objExcel->getActiveSheet()->setCellValueExplicit('F'.($i+2),$epl[$i]['q6']);
            $objExcel->getActiveSheet()->setCellValueExplicit('G'.($i+2),$epl[$i]['name']);
            $objExcel->getActiveSheet()->setCellValueExplicit('H'.($i+2),$epl[$i]['phone']);
            $objExcel->getActiveSheet()->setCellValueExplicit('I'.($i+2),$epl[$i]['jiang']);
        }


        //*************************************
        //设置单元格样式
        //

        //设置宽度
        $objActSheet->getColumnDimension('A')->setWidth(20);
        $objActSheet->getColumnDimension('B')->setWidth(25);
        $objActSheet->getColumnDimension('C')->setWidth(20);
        $objActSheet->getColumnDimension('D')->setWidth(20);
        $objActSheet->getColumnDimension('E')->setWidth(20);
        $objActSheet->getColumnDimension('F')->setWidth(20);
        $objActSheet->getColumnDimension('G')->setWidth(20);
        $objActSheet->getColumnDimension('H')->setWidth(20);
        $objActSheet->getColumnDimension('I')->setWidth(20);

        //设置字体
        $objStyleA = $objActSheet->getStyle('A');
        $objStyleA = $objStyleA->getFont();
        $objStyleA->setName('宋体');
        $objStyleA->setSize(10);
        $objStyleA->setBold(true);
        $objStyleA->getColor()->setARGB('FF999999');

        //*************************************
        //输出内容

        $outputFileName = $fileName;
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header('Content-Disposition:attachment;filename="' . $outputFileName . '"');//兼容其他浏览器到文件
        header('Content-Disposition:filename="' . $outputFileName . '"');  //兼容IE浏览器到文件
        header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
        header("Content-Transfer-Encoding: binary");
        header("Expires: 0");
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Pragma: no-cache");
        $objWriter->save('./excel/'.$outputFileName);
        echo $outputFileName;
    }

    /*导出所有售前问卷记录*/
    public function shouqianExportALL()
    {
        // 引入库文件
        \think\Loader::import('Excel.PHPExcel');
        \think\Loader::import('Excel.PHPExcel.IOFactory');
        
        $map['id']   = ['>' , 1];
        $map['type'] = 2;
        $epls[] = db('wenjuan')->where($map)->select();
        $epl    = $epls[0];
 
        // print_r($epl);die;
        // 拼接文件名
        $fileName = "quanbuShouqian".date("Ymd-His",time()).".xls";
        
        $objExcel = new \PHPExcel();  // 创建一个处理对象实例
        // 创建文件格式写入对象实例, uncomment
        $objWriter = new \PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式

        //*************************************
        //设置文档基本属性
        $objProps = $objExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        //*************************************
        //设置当前的sheet索引，用于后续的内容操作。
        //一般只有在使用多个sheet的时候才需要显示调用。
        //缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0

        $objExcel->setActiveSheetIndex(0);
        $objActSheet = $objExcel->getActiveSheet();

        //设置当前活动sheet的名称
        $objActSheet->setTitle("问卷记录");

        //设置单元格首格内容
        $objActSheet->setCellValue('A1','能否达到预期效果');
        $objActSheet->setCellValue('B1','是否在约定时间内到达');
        $objActSheet->setCellValue('C1','服务态度如何');
        $objActSheet->setCellValue('D1','功能讲解如何');
        $objActSheet->setCellValue('E1','需要提升的地方');
        $objActSheet->setCellValue('F1','客户公司名称');
        $objActSheet->setCellValue('G1','客户姓名');
        $objActSheet->setCellValue('H1','客户手机号码');
        $objActSheet->setCellValue('I1','获得奖品');

        //  遍历访客信息数组，将数据存入对应的excel文件的每个单元格
        for($i = 0; $i < count($epl); $i++)
        {
            $objExcel->getActiveSheet()->setCellValueExplicit('A'.($i+2),$epl[$i]['q1']);
            $objExcel->getActiveSheet()->setCellValueExplicit('B'.($i+2),$epl[$i]['q2']);
            $objExcel->getActiveSheet()->setCellValueExplicit('C'.($i+2),$epl[$i]['q3']);
            $objExcel->getActiveSheet()->setCellValueExplicit('D'.($i+2),$epl[$i]['q4']);
            $objExcel->getActiveSheet()->setCellValueExplicit('E'.($i+2),$epl[$i]['q5']);
            $objExcel->getActiveSheet()->setCellValueExplicit('F'.($i+2),$epl[$i]['q6']);
            $objExcel->getActiveSheet()->setCellValueExplicit('G'.($i+2),$epl[$i]['name']);
            $objExcel->getActiveSheet()->setCellValueExplicit('H'.($i+2),$epl[$i]['phone']);
            $objExcel->getActiveSheet()->setCellValueExplicit('I'.($i+2),$epl[$i]['jiang']);
        }


        //*************************************
        //设置单元格样式
        //

        //设置宽度
        $objActSheet->getColumnDimension('A')->setWidth(20);
        $objActSheet->getColumnDimension('B')->setWidth(25);
        $objActSheet->getColumnDimension('C')->setWidth(20);
        $objActSheet->getColumnDimension('D')->setWidth(20);
        $objActSheet->getColumnDimension('E')->setWidth(20);
        $objActSheet->getColumnDimension('F')->setWidth(20);
        $objActSheet->getColumnDimension('G')->setWidth(20);
        $objActSheet->getColumnDimension('H')->setWidth(20);
        $objActSheet->getColumnDimension('I')->setWidth(20);

        //设置字体
        $objStyleA = $objActSheet->getStyle('A');
        $objStyleA = $objStyleA->getFont();
        $objStyleA->setName('宋体');
        $objStyleA->setSize(10);
        $objStyleA->setBold(true);
        $objStyleA->getColor()->setARGB('FF999999');

        //*************************************
        //输出内容

        $outputFileName = $fileName;
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header('Content-Disposition:attachment;filename="' . $outputFileName . '"');//兼容其他浏览器到文件
        header('Content-Disposition:filename="' . $outputFileName . '"');  //兼容IE浏览器到文件
        header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
        header("Content-Transfer-Encoding: binary");
        header("Expires: 0");
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Pragma: no-cache");
        $objWriter->save('./excel/'.$outputFileName);
        echo $outputFileName;
    }

    /*清空所有售前问卷记录*/
    public function shouqianDelAll()
    {
        $map['id']   = ['>' , 1];
        $map['type'] = 2;
        $delid = db( 'wenjuan' )->where( $map )->column( 'id' );
        $dels  = db( 'wenjuan' )->delete( $delid );
        print_r( $dels );
    }

	/*显示售后问卷*/
	public function shouhou()
	{
        // 查找售后问卷，分页显示
		$shouhou = db( 'wenjuan' )->where( 'type', 3 )->paginate( 5 );
        $this->assign( 'list', $shouhou );
        return $this->fetch();	
	}

    /*新增售后问卷对象*/
    public function shouhouAdd()
    {
        if( Request()->isPost() )
        {
            // 获取表单数据
            $data = [
                'name' => input( 'post.name' ),
                'phone'=> input( 'post.phone' ),
                'type' => 3,
            ];
            // 查看是否有没有填写的用户信息
            $wenjuan = db( 'wenjuan' )->where( [ 'phone'=>$data['phone'], 'flag'=>0, 'type' =>3 ] )->find();
            // print_r( $wenjuan );die;
            if( $wenjuan )
            {
                // 存在未处理记录，没有必要添加
                $this->error( '用户还没有填写问卷，请不用着急再次添加' );
            } else {
                // 没有存在未处理记录，添加记录
                $res = db( 'wenjuan' )->insert( $data );              
            }
            // 判断插入数据是否成功
            if( $res )
            {
                // 插入数据成功
                $this->success( '添加成功' , 'shouhou' );
            } else {
                // 插入数据失败
                $this->error( '添加失败' );
            }
            // print_r( $data );
        } else {
            return $this->fetch();
        }
    }

    /*清空所有售后问卷记录*/
    public function shouhouDelAll()
    {

        $map['id']   = ['>' , 1];
        $map['type'] = 3;
        $delid = db( 'wenjuan' )->where( $map )->column( 'id' );
        $dels  = db( 'wenjuan' )->delete( $delid );
        print_r( $dels );
    }

    // 售后详细信息
    public function shouhouDetail()
    {
        $id      = input( 'id' ); 
        $shouhou = db( 'wenjuan' )->where( 'id',input( 'id' ) )->find();
        $this->assign( 'type', '售后调查问卷' );
        $this->assign( 'list', $shouhou );
        return $this->fetch( 'shouhoudetail' ); 
    }

    /*导出选定售后问卷记录*/
    public function shouhouExport()
    {
        // 引入库文件
        \think\Loader::import('Excel.PHPExcel');
        \think\Loader::import('Excel.PHPExcel.IOFactory');
        
        $id[] = input('post.id/a');
        // print_r($id);die;
        for($i=0 ; $i<count($id[0]) ; $i++)
        {
            $epl[] = db('wenjuan')->where('id',$id[0][$i])->find();
        }
        // print_r($epl);die;
        // 拼接文件名
        $fileName = "bufenShouhou".date("Ymd-His",time()).".xls";


        $objExcel = new \PHPExcel();  // 创建一个处理对象实例
        // 创建文件格式写入对象实例, uncomment
        $objWriter = new \PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式

        //*************************************
        //设置文档基本属性
        $objProps = $objExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        //*************************************
        //设置当前的sheet索引，用于后续的内容操作。
        //一般只有在使用多个sheet的时候才需要显示调用。
        //缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0

        $objExcel->setActiveSheetIndex(0);
        $objActSheet = $objExcel->getActiveSheet();

        //设置当前活动sheet的名称
        $objActSheet->setTitle("问卷记录");

        //设置单元格首格内容
        $objActSheet->setCellValue('A1','客户角色');
        $objActSheet->setCellValue('B1','产品使用频率');
        $objActSheet->setCellValue('C1','日常来访接待量');
        $objActSheet->setCellValue('D1','服务评价');
        $objActSheet->setCellValue('E1','需要提升的地方');
        $objActSheet->setCellValue('F1','客户公司名称');
        $objActSheet->setCellValue('G1','客户姓名');
        $objActSheet->setCellValue('H1','客户手机号码');
        $objActSheet->setCellValue('I1','获得奖品');

        //  遍历访客信息数组，将数据存入对应的excel文件的每个单元格
        for($i = 0; $i < count($epl); $i++)
        {
            $objExcel->getActiveSheet()->setCellValueExplicit('A'.($i+2),$epl[$i]['q1']);
            $objExcel->getActiveSheet()->setCellValueExplicit('B'.($i+2),$epl[$i]['q2']);
            $objExcel->getActiveSheet()->setCellValueExplicit('C'.($i+2),$epl[$i]['q3']);
            $objExcel->getActiveSheet()->setCellValueExplicit('D'.($i+2),$epl[$i]['q4']);
            $objExcel->getActiveSheet()->setCellValueExplicit('E'.($i+2),$epl[$i]['q5']);
            $objExcel->getActiveSheet()->setCellValueExplicit('F'.($i+2),$epl[$i]['q6']);
            $objExcel->getActiveSheet()->setCellValueExplicit('G'.($i+2),$epl[$i]['name']);
            $objExcel->getActiveSheet()->setCellValueExplicit('H'.($i+2),$epl[$i]['phone']);
            $objExcel->getActiveSheet()->setCellValueExplicit('I'.($i+2),$epl[$i]['jiang']);
        }


        //*************************************
        //设置单元格样式
        //

        //设置宽度
        $objActSheet->getColumnDimension('A')->setWidth(20);
        $objActSheet->getColumnDimension('B')->setWidth(25);
        $objActSheet->getColumnDimension('C')->setWidth(20);
        $objActSheet->getColumnDimension('D')->setWidth(20);
        $objActSheet->getColumnDimension('E')->setWidth(20);
        $objActSheet->getColumnDimension('F')->setWidth(20);
        $objActSheet->getColumnDimension('G')->setWidth(20);
        $objActSheet->getColumnDimension('H')->setWidth(20);
        $objActSheet->getColumnDimension('I')->setWidth(20);

        //设置字体
        $objStyleA = $objActSheet->getStyle('A');
        $objStyleA = $objStyleA->getFont();
        $objStyleA->setName('宋体');
        $objStyleA->setSize(10);
        $objStyleA->setBold(true);
        $objStyleA->getColor()->setARGB('FF999999');

        //*************************************
        //输出内容

        $outputFileName = $fileName;
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header('Content-Disposition:attachment;filename="' . $outputFileName . '"');//兼容其他浏览器到文件
        header('Content-Disposition:filename="' . $outputFileName . '"');  //兼容IE浏览器到文件
        header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
        header("Content-Transfer-Encoding: binary");
        header("Expires: 0");
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Pragma: no-cache");
        $objWriter->save('./excel/'.$outputFileName);
        echo $outputFileName;
    }  

    /*导出所有售后问卷记录*/
    public function shouhouExportALL()
    {
        // 引入库文件
        \think\Loader::import('Excel.PHPExcel');
        \think\Loader::import('Excel.PHPExcel.IOFactory');
        
        $map['id']   = ['>' , 1];
        $map['type'] = 3;
        $epls[] = db('wenjuan')->where($map)->select();
        $epl    = $epls[0];
        // print_r($epl);die;
        // 拼接文件名
        $fileName = "quanbuShouhou".date("Ymd-His",time()).".xls";


        $objExcel = new \PHPExcel();  // 创建一个处理对象实例
        // 创建文件格式写入对象实例, uncomment
        $objWriter = new \PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式

        //*************************************
        //设置文档基本属性
        $objProps = $objExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        //*************************************
        //设置当前的sheet索引，用于后续的内容操作。
        //一般只有在使用多个sheet的时候才需要显示调用。
        //缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0

        $objExcel->setActiveSheetIndex(0);
        $objActSheet = $objExcel->getActiveSheet();

        //设置当前活动sheet的名称
        $objActSheet->setTitle("问卷记录");

        //设置单元格首格内容
        $objActSheet->setCellValue('A1','客户角色');
        $objActSheet->setCellValue('B1','产品使用频率');
        $objActSheet->setCellValue('C1','日常来访接待量');
        $objActSheet->setCellValue('D1','服务评价');
        $objActSheet->setCellValue('E1','需要提升的地方');
        $objActSheet->setCellValue('F1','客户公司名称');
        $objActSheet->setCellValue('G1','客户姓名');
        $objActSheet->setCellValue('H1','客户手机号码');
        $objActSheet->setCellValue('I1','获得奖品');

        //  遍历访客信息数组，将数据存入对应的excel文件的每个单元格
        for($i = 0; $i < count($epl); $i++)
        {
            $objExcel->getActiveSheet()->setCellValueExplicit('A'.($i+2),$epl[$i]['q1']);
            $objExcel->getActiveSheet()->setCellValueExplicit('B'.($i+2),$epl[$i]['q2']);
            $objExcel->getActiveSheet()->setCellValueExplicit('C'.($i+2),$epl[$i]['q3']);
            $objExcel->getActiveSheet()->setCellValueExplicit('D'.($i+2),$epl[$i]['q4']);
            $objExcel->getActiveSheet()->setCellValueExplicit('E'.($i+2),$epl[$i]['q5']);
            $objExcel->getActiveSheet()->setCellValueExplicit('F'.($i+2),$epl[$i]['q6']);
            $objExcel->getActiveSheet()->setCellValueExplicit('G'.($i+2),$epl[$i]['name']);
            $objExcel->getActiveSheet()->setCellValueExplicit('H'.($i+2),$epl[$i]['phone']);
            $objExcel->getActiveSheet()->setCellValueExplicit('I'.($i+2),$epl[$i]['jiang']);
        }


        //*************************************
        //设置单元格样式
        //

        //设置宽度
        $objActSheet->getColumnDimension('A')->setWidth(20);
        $objActSheet->getColumnDimension('B')->setWidth(25);
        $objActSheet->getColumnDimension('C')->setWidth(20);
        $objActSheet->getColumnDimension('D')->setWidth(20);
        $objActSheet->getColumnDimension('E')->setWidth(20);
        $objActSheet->getColumnDimension('F')->setWidth(20);
        $objActSheet->getColumnDimension('G')->setWidth(20);
        $objActSheet->getColumnDimension('H')->setWidth(20);
        $objActSheet->getColumnDimension('I')->setWidth(20);

        //设置字体
        $objStyleA = $objActSheet->getStyle('A');
        $objStyleA = $objStyleA->getFont();
        $objStyleA->setName('宋体');
        $objStyleA->setSize(10);
        $objStyleA->setBold(true);
        $objStyleA->getColor()->setARGB('FF999999');

        //*************************************
        //输出内容

        $outputFileName = $fileName;
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header('Content-Disposition:attachment;filename="' . $outputFileName . '"');//兼容其他浏览器到文件
        header('Content-Disposition:filename="' . $outputFileName . '"');  //兼容IE浏览器到文件
        header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
        header("Content-Transfer-Encoding: binary");
        header("Expires: 0");
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Pragma: no-cache");
        $objWriter->save('./excel/'.$outputFileName);
        echo $outputFileName;
    }  

    /*售后问卷调查设置*/
    public function shouhouSettings()
    {
        // 判断时候是POST方式提交数据
        if( Request()->isPost())
        {
            // 获取表单数据
            $data = [
                'jiang_1_name'=> input( 'post.jiang_1_name' ),
                'jiang_1_num' => input( 'post.jiang_1_num' ),                
                'jiang_2_name'=> input( 'post.jiang_2_name' ),
                'jiang_2_num' => input( 'post.jiang_2_num' ),
                'type'        => 3,
                'status'      => 1,
                'jiang_1_rest'=>input( 'post.jiang_1_num' ),
                'jiang_2_rest'=>input( 'post.jiang_2_num' ),
                'jiang_1_winning' => input( 'post.jiang_1_winning' ),
                'jiang_2_winning' => input( 'post.jiang_2_winning' ),

            ];
            // print_r($data);die;

            // 判断这条设置是否已经存在
            $shouhou = db( 'wenjuansettings' )->where( $data )->find();
            if( $shouhou )
            {   
                // 这条设置已经存在，提示错误信息，返回前端页面
                return $this->error( '您并没有修改问卷设置，请检查设置之后再提交' );
            } else {
                // 当前期数不存在，新增当前设置
                $data['create_time'] = time();
                $res = db( 'wenjuansettings' )->insert( $data );
                // 判断新增数据是否成功
                if( $res )
                {
                    // 数据操作成功
                    return $this->success( '设置成功' );
                } else {
                    // 数据操作失败
                    return $this->error( '设置失败，请稍后再试' );
                }
            }
        } else {
            // 不是POST方式提交数据
            // 获取当前设置
            $list = db( 'wenjuansettings' )->where( 'type', 3 )->order( 'id desc' )->limit( 1 )->find();
            $this->assign( 'list', $list );
            return $this->fetch();
        }
    }
}
